# -*- coding: utf-8 -*-
"""dashboard-financeiro-python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mh-T7qZnwqaaBHyUgk6gAgHg5pTx6Ixu
"""

# Dashboard Financeiro Simples
# Autora: Ana Luiza de Souza Gomes

import pandas as pd
import matplotlib.pyplot as plt

def carregar_dados():
    try:
        df = pd.read_csv('financeiro.csv')
        return df
    except Exception as e:
        print(f"Erro ao carregar arquivo: {e}")
        return None

def calcular_resumo(df):
    receitas = df[df['tipo'] == 'receita']['valor'].sum()
    despesas = df[df['tipo'] == 'despesa']['valor'].sum()
    saldo = receitas - despesas

    print("\n RESUMO FINANCEIRO")
    print(f"Receitas: R$ {receitas}")
    print(f"Despesas: R$ {despesas}")
    print(f"Saldo: R$ {saldo}")

    return receitas, despesas

def grafico_despesas(df):
    despesas = df[df['tipo'] == 'despesa']
    resumo = despesas.groupby('categoria')['valor'].sum()

    resumo.plot(kind='bar')
    plt.title('Despesas por Categoria')
    plt.xlabel('Categoria')
    plt.ylabel('Valor')
    plt.xticks(rotation=45)

    plt.show()

def main():
    df = carregar_dados()

    if df is not None:
        calcular_resumo(df)
        grafico_despesas(df)

if __name__ == "__main__":
    main()

from google.colab import files
uploaded = files.upload()